### ISSUE TITLE
SelectListView example - atom.workspaceView.append(this)

### ISSUE THREAD

**Issue by fentas** [atom/atom-space-pen-views#11]
Hi there,
I am a little bit confused.
The given example ([README.md](https://github.com/atom/atom-space-pen-views/blob/master/README.md)) uses ```atom.workspaceView.append(this)```. 

But deprecations make clear that this will be no longer available.
Is there any update? How should it look like?

Greetings, fentas

> atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.

**Comment by fentas** [comment]
I guess I found the solution here [upgrading-to-1-0-apis-upgrading-your-package](https://atom.io/docs/v0.202.0/upgrading-to-1-0-apis-upgrading-your-package).
Simply *replace* 
```
atom.workspaceView.append(this)
``` 
*with*
```
@panel ?= atom.workspace.addModalPanel(item: this) 
@panel.show()
```

And add ```cancelled``` method.

Cheers, fentas
plz. update README.md

**Comment by benogle** [comment]
Thanks for the heads up!
