### ISSUE TITLE
requiring atom-space-pen-views adds 100ms to my package startup time

### ISSUE THREAD

**Issue by noseglid** [atom/atom-space-pen-views#12]
I'm trying to get down the load times of my package [atom-build](https://atom.io/packages/build). It is written in JavaScript (not CoffeeScript). It requires atom-space-pen-views for SelectListView and the generic view (from `space-pen`).

I have this line in my package: `var View = require('atom-space-pen-views').View`, when I toggle it I see very different load times in my package (per measurements with TimeCop).

With: ![screen shot 2015-07-01 at 22 07 10](https://cloud.githubusercontent.com/assets/933880/8463832/fa6249c4-203d-11e5-8cb6-31903f1385a2.png)

Without: ![screen shot 2015-07-01 at 22 06 53](https://cloud.githubusercontent.com/assets/933880/8463840/04bc9eec-203e-11e5-9835-cbd3ec5f869e.png)

Other packages doesn't seem to suffer from this. What could cause this?

**Comment by benogle** [comment]
Yeah, it is common for requires to take a bunch of time. 

One thing you can do is defer the requires until you absolutely need them. Many packages use this pattern:

https://github.com/atom/bracket-matcher/blob/master/lib/main.coffee#L1

then https://github.com/atom/bracket-matcher/blob/master/lib/main.coffee#L20-L21

**Comment by benogle** [comment]
It's not ideal. Sorry about this. A new view framework will be a help, and improving the package loading to make many packages load async would help too.

**Comment by noseglid** [comment]
I see. I will defer my requires until I really need them. It is somewhat successful. Thanks for the swift response!
