### ISSUE TITLE
npm package.json parse error for 2.0.5

### ISSUE THREAD

**Issue by tomalec** [atom/atom-space-pen-views#13]
I'm trying to install Glavin001/atom-beautify what results in following error:
```log
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\tomalec\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\tomalec\\AppData\\Local\\atom\\app-1.0.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\tomalec\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\tomalec\\.atom\\.apmrc" "install" "C:\\Users\\tomalec\\AppData\\Local\\Temp\\d-11569-12428-10amrqu\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! file C:\Users\tomalec\.atom\.apm\atom-space-pen-views\2.0.5\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 
npm ERR! File: C:\Users\tomalec\.atom\.apm\atom-space-pen-views\2.0.5\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
```

Do you have any idea how to get it work?

**Comment by thomasjo** [comment]
Have you looked at the contents of `C:\Users\tomalec\.atom\.apm\atom-space-pen-views\2.0.5\package\package.json`? Seems like the file might have gotten corrupted during download.

**Comment by tomalec** [comment]
Thanks, for the response, yes file was corrupted, I've removed entire `C:\Users\tomalec\.atom\.apm\atom-space-pen-views`, and now I'm stuck at
https://github.com/atom/settings-view/issues/577

**Comment by tomalec** [comment]
Cleaning `.apm` folder manually helped. (`apm install ...`, and `rm -rf /path/to/corrupted/dependency`)

**Comment by michaelaye** [comment]
Could you elaborate that cleaning procedure a bit for people that don't usually use the apm or npm commands? I'm fine with using the Terminal, but I'm scared to destroy some package databases doing it wrong (been burned with that too often with dpkg).

**Comment by tomalec** [comment]
To be honest, that was my first attempt to use apm. I simply called `rm -r
path/to/conflicting/pckg´
13 sie 2015 21:43 "K.-Michael Aye" <notifications@github.com> napisał(a):
