### ISSUE TITLE
Recommended alternative to deprecated space-pen-views

### ISSUE THREAD

**Issue by ShMcK** [atom/atom-space-pen-views#16]
`TextEditorView, SelectListView, and ScrollView exports from the atom module are now deprecated will soon be removed, but can still be used in packages by depending on this library in your package.json.`

Is there a recommended alternative for space-pen-views? 
Will space-pen-views continue to be supported?

**Comment by mnquintana** [comment]
Not yet - you'll want to follow https://github.com/atom/atom/issues/5756 for updates on this.
