### ISSUE TITLE
Back and forward arrow keys and delete keys not work on osx

### ISSUE THREAD

**Issue by unbug** [atom/atom-space-pen-views#17]
I open a webview in it,but back and forward arrow keys and delete keys not work on osx,delete key only work with CTRL.
My package [https://atom.io/packages/codelf](https://atom.io/packages/codelf)

**Comment by lee-dohm** [comment]
I don't think this is due to atom-space-pen-views, you might want to take a look at the native-key-bindings fix:

https://discuss.atom.io/t/backspace-isnt-working-in-regular-text-fields/11020/2?u=leedohm

**Comment by unbug** [comment]
@lee-dohm Thanks,problem solved
