### ISSUE TITLE
install failing

### ISSUE THREAD

**Issue by willnwhite** [atom/atom-space-pen-views#19]
I'm doing

> $ apm install atom-space-pen-views

I'm getting back

```
Installing atom-space-pen-views to /Users/.../.atom/packages ✗
Request for package information failed: Not Found
```

Can apm install other packages.

**Comment by thomasjo** [comment]
This is not an Atom package, so you cannot install it in that manner. Add it to the dependency list in your package's `package.json` file, then invoke `apm install` from the package root directory.

**Comment by willnwhite** [comment]
Thanks, and sorry. I had no idea.
